config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users
  resources :users
  resources :events do
    resources :attendances
  end 
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :attendance_send

  belongs_to :event
  belongs_to :user

  def attendance_send
    event = self.event
    admin = event.admin
    UserMailer.attendance_email(admin, event).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: "User" #User admin
  has_many :attendances
  has_many :users, through: :attendances #User participants

  validates :start_date, presence: true, if: :future_date
  
  validates :duration, presence: true, numericality: {greater_than: 0}, if: :is_multiple? #multiple de 5, et est strictement positif
  validates :title, presence: true, length: { in: 5..140 } #doit faire au moins 5 caractères et maxi 140 caractères.
  validates :description, presence: true, length: { in: 20..1000 } #doit faire entre 20 et 1000 caractères.
  validates :price, presence: true, :inclusion => 1..1000 #doit être compris entre 1 et 1000.
  validates :location, presence: true

  def is_multiple?
    if duration % 5 != 0
      errors.add(:duration, "must be a multiple of 5") 
    end
  end

  def future_date
    errors.add(:start_date, "Event can't be in the past") unless start_date > DateTime.now
  end

  def amount
    self.price * 100
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  #has_secure_password

  has_many :attendances
  has_many :events, through: :attendances

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :encrypted_password, presence: true, length: {minimum: 6}
  #validates :description, presence: true
  #validates :first_name, presence: true
  #validates :last_name, presence: true

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :event, only: [:index, :create, :new]
  before_action :authenticate_user!

  def index
    @attendances = @event.attendances
  end

  def new
    @attendance = Attendance.new
  end

  def create

    @amount = @event.amount
    begin
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
    
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement participation évènement',
      currency: 'eur',
      })
      
      new_a = Attendance.new(event: @event, stripe_customer_id: customer.id)
      puts "$" * 50
      puts current_user.id
      puts new_a
      puts "$" * 50
      new_a.user_id = current_user.id
      new_a.save

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_attendance_path
    end
  end

  def event
    @event = Event.find_by(id: params[:event_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(post_params)
    @event.admin = current_user
    if @event.save
      redirect_to event_path(@event.id), success: "Evénement créé avec succès !"
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def event
    @event = Event.find_by(id: params[:event_id])
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Il faut s'enregistrer bb"
      redirect_to new_user_session_path
    end
  end

  def post_params
    post_params = params.require(:event).permit(:title, :location, :description, :start_date, :price, :duration)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @events = Event.where(admin: @user)
  end

  def edit
    @user = current_user
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profil édité !"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "Impossible d'éditer le profil :"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<div class="container">
  <br>
  <h2> ✅ Validation du paiement de <strong><%=@event.price%> euros</strong>!</h2>
  <br>
  <h2>Votre participation à l'évènement <strong>"<%=@event.title%>"</strong>, le <%=@event.start_date%> est confirmée.</h2>
</div>

app/views/attendances/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <br>
      <h2>Gérer ton évènement "<%=@event.title %>"</h2>
      <br>
      <h3>📅  Date de début : <%=@event.start_date %></h3>
      <h3>📍 Lieu : <%= @event.location %></h3>
      <h3>⏱ Durée : <%=@event.duration %> minutes</h3>
      <h3>💰 Prix : <%= @event.price %>€</h3>
      <h3>❓ Description : <%= @event.description %></h3>
      <br>
      <%= link_to "Editer l'évènement", edit_event_path(@event.id), class: "btn btn-light btn-lg" %>
      <%= link_to "Supprimer l'évènement", event_path(@event.id), :class => "btn btn-light btn-lg", :method => 'DELETE', :data => {:confirm => 'Sûr ?'} %>
    </div>

    <div class="col-md-6">
      <br>
      <h2 class="text-center">Les participants</h2>

          <% @attendances.each do |a| %>
            <div class="card-deck mx-auto">
              <div class="card mb-4 shadow-sm">
                <div class="card-header">
                  <h4 class="my-0 font-weight-normal"></h4>
                  <h4 class="my-0 font-weight-normal"></h4>
                </div>
                <div class="card-body">
                  <div class="text-wrap bd-highlight" style="width: 15rem;">
                    <ul class="list-unstyled mt-3 mb-4">
                      <li>First name : <%= a.user.first_name ? a.user.first_name : "Not mentionned" %></li>
                      <li>First name : <%= a.user.first_name ? a.user.first_name : "Not mentionned" %></li>
                      <li>Last name : <%= a.user.last_name ? a.user.last_name : "Not mentionned" %></li>
                      <li>Email : <%= a.user.email ? a.user.email : "Not mentionned" %></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="container">
  <br><br>
  <h2>S'inscrire à l'évènement <%=@event.title%>, le <%=@event.start_date%> !</h2>

  <%= form_tag event_attendances_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Prix : <%=@event.price%> euros</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Paiement inscription"
      data-amount=<%=@event.amount%>
      data-currency="eur"
      data-locale="auto"></script>
  <% end %>

</div>

app/views/events/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br>

      <%= form_for @event, html: { class: "form-signin mt-3" } do |f| %>
        
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifie ton évènement</h1>
        
        <div class="form-group">
          <%= f.label :start_date, "Date" %> 
          <%= f.datetime_field :start_date, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :duration, "Durée (doit être un multiple de 5)" %> 
          <%= f.text_field :duration, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :title, "Titre (entre 50 et 140 caractères)" %> 
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description (entre 20 et 1000 caractères)" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :price, "Prix (entre 1 et 1000 €)" %>
          <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :location, "Lieu" %><br />
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Enregister les modifications", class: "btn btn-lg btn-danger btn-block" %>
        </div>
      <% end %>

      <br><br>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  
  <!-- JUMBOTRON -->
  <div class="jumbotron jumbotron-fluid background-image">
    <div class="container text-center">
      <h1 class="display-4 mt-5">EvenTop</h1>
      <h2 class="lead">Créer des évènements inoubliables</h2>
      <br >   
      <%= link_to "Créer un évènement", new_event_path, class: "btn btn-light btn-lg" %>
    </div>
  </div>

  <!-- TOUS LES EVENTS -->
  <div class="row">
    <% @events.each_with_index do |event, i| %>
      <div class="card-deck mx-auto text-center">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Evènement <%= event.id %></h4>
          </div>
          <div class="card-body">
          <div class="text-wrap bd-highlight" style="width: 15rem;">
            <ul class="list-unstyled mt-3 mb-4">
              <li>Titre: <%= event.title %></li>
              <br>
              <li>Description: <%= event.description %></li>
            </ul>
          <%= link_to "Découvre l'évènement", event_path(event.id), class: "btn btn-lg btn-block btn-outline-danger" %>
          </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<!-- Si erreur -->
<% if @event.errors.any? %>
  <div class="alert alert-danger text-center" role="alert">
    <p>Nous n'avons pas réussi à créer l'évènement pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br>

      <%= form_for @event, html: { class: "form-signin mt-3" } do |f| %>
        
        <h1 class="h3 mb-3 font-weight-normal text-center">Crée un évènement</h1>
        
        <div class="form-group">
          <%= f.label :start_date, "Date" %> 
          <%= f.datetime_field :start_date, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :duration, "Durée (doit être un multiple de 5)" %> 
          <%= f.text_field :duration, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label :title, "Titre (entre 50 et 140 caractères)" %> 
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description (entre 20 et 1000 caractères)" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :price, "Prix (entre 1 et 1000 €)" %>
          <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :location, "Lieu" %><br />
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Create", class: "btn btn-lg btn-danger btn-block" %>
        </div>
      <% end %>

      <br><br>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- JUMBOTRON -->
<div class="jumbotron jumbotron-fluid background-image" id="showshow">
  <div class="container text-center">
    <h1 class="display-4 mt-5">Événement <%=@event.title%></h1>
    <br>
    <h2><%= @event.attendances.count %> <%= (@event.attendances.count) == 1 ? 'Participant' : 'Participants'%></h2> 
    
    <% if current_user == @event.admin %>
    <%= link_to "Gérer mon évènement", event_attendances_path(@event.id), class: "btn btn-light btn-lg" %>
    <% else %>
    <%= link_to "Rejoindre cet évènement", new_event_attendance_path(@event.id), class: "btn btn-light btn-lg" %>
    <% end %>
    
  </div>
</div>

<div class="container" style= "margin-bottom: 45px">
  <div class="row">
    <div class="col-sm-12">
      <h3>📅  Date de début : <%=@event.start_date %></h3>
      <h3>📍 Lieu : <%= @event.location %></h3>
      <h3>⏱ Durée : <%=@event.duration %> minutes</h3>
      <h3>💰 Prix : <%= @event.price %>€</h3>
      <h3>❓ Description : <%= @event.description %></h3>
      <% if current_user == @event.admin %>
      <h3>👤 Orgnanisé par : Moi </h3>
      <% else %>
      <h3>👤 Orgnanisé par : <%= @event.admin.first_name %> <%= @event.admin.last_name %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- BOOTSWATCH -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/simplex/bootstrap.min.css" integrity="sha384-FYrl2Nk72fpV6+l3Bymt1zZhnQFK75ipDqPXK0sOR0f/zeOSZ45/tKlsKucQyjSp" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!-- NAVBAR -->
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "EventTop", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Créer un événement", new_event_path, :class => "nav-item nav-link" %>
          </li>
        </ul>

        <div class="dropdown">
          <% if current_user == nil %>
            <form class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">S'inscrire / Se connecter</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path, :class => "nav-item nav-link" %></a>
                <a class="dropdown-item" <%= link_to "S'inscrire", new_user_registration_path, :class => "nav-item nav-link" %></a>
              </div>
            </form>
          <% else %>
            <form class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon profil</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" <%= link_to "Mon profil", user_path(current_user.id), :class => "nav-item nav-link" %></a>
                <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, :class => "btn btn-outline-danger", :method => 'DELETE' %></a>
              </div>
            </form>
          <% end %>
        </div>
      </div>
    </nav>

    <!-- VIEWS -->
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @user, html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Compléter/Modifier mon profil</h1>
        <div class="form-group">
          <%= f.label :first_name, "Prénom" %><br />
          <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Nom" %><br />
          <%= f.text_field:last_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Enregistrer", class: "btn btn-md btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Profil</title>
  </head>
<body>

  <div class="container">
    <div class="text-center">
      <br>
      <h1> Profil</h1>
      <br>
      <!--image-->
        <div class="avatar mx-auto white">
          <img src="https://picsum.photos/200" class="rounded-circle">
        </div>
      <br>

      <!--text-->
      <div class="card-body">
      <h3 class="font-weight-light"><span class="text-secondary"><% if current_user.first_name != nil%> <%= @user.first_name%> <% end%> <% if current_user.last_name != nil%> <%= @user.last_name%> <% end%></span>
       <hr>
      <h6 class="font-weight-bold">Description: </h6> <p class="text-secondary">Description<%= @user.description %></p>
      <h6 class="font-weight-bold">Email: </h6> <p class="text-secondary"><%= @user.email %></p>
      </div>

      <!--boutons-->
      <%= link_to "Editer mes informations", edit_user_path(@user), :class => "btn btn-primary" %>
      <%= link_to "Editer mes identifiants", edit_user_registration_path(@user), :class => "btn btn-secondary" %>
    </div>
  </div>

  </body>